name: Reusable - Handle Labeled Issues

on:
  workflow_call:

permissions:
  issues: write

jobs:
  handle-label:
    runs-on: ubuntu-latest
    steps:
      - name: Print labeled issue info
        run: echo "This issue was labeled. Running reusable workflow from doppar/doppar."
